language: swift
osx_image: xcode9.4.1
script:
    - xcodebuild clean test -workspace messenger-app.xcworkspace -scheme messenger-appTests -destination "platform=iOS Simulator,name=iPhone 8 Plus,OS=11.4"
install:
  - pod install
